version: "3"
services:
  postgres:
    image: postgres:9.6.5
    container_name: postgres
    env_file:
      - docker.env
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
  blog_sample:
    build: .
    container_name: blog_sample
    command: app
    env_file:
      - docker.env
    volumes:
      - /tmp/blog_sample/public/uploads:/var/www/blog_sample/public/uploads
    ports:
      - "8070:8080"
    external_links:
      - postgres:postgres
