version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - docker.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  blog_sample:
    build: .
    container_name: blog_sample
    command: app
    env_file:
      - docker.env
    ports:
      - "8070:8080"
    external_links:
      - postgres:postgres
